CREATE TABLE [Staging].[STG_Refund] (
    [RefundID]                  INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name]                      NVARCHAR (256)  NULL,
    [Description]               NVARCHAR (4000) NULL,
    [CreatedDate]               DATETIME        NOT NULL,
    [CreatedBy]                 INT             NOT NULL,
    [CreatedExtractNumber]      INT             NOT NULL,
    [LastModifiedDate]          DATETIME        NOT NULL,
    [LastModifiedBy]            INT             NOT NULL,
    [LastModifiedExtractNumber] INT             NOT NULL,
    [ArchivedInd]               BIT             DEFAULT ((0)) NOT NULL,
    [SourceCreatedDate]         DATETIME        NOT NULL,
    [SourceModifiedDate]        DATETIME        NOT NULL,
    [InformationSourceID]       INT             NOT NULL,
    [CustomerID]                INT             NOT NULL,
    [SalesTransactionID]        INT             NULL,
    [RefundNumber]              NVARCHAR (16)   NULL,
    [RetailChannelID]           INT             NOT NULL,
    [RefundDate]                DATETIME        NOT NULL,
    [RefundReasonCodeID]        INT             NULL,
    [RefundDecisionCodeID]      INT             NULL,
    [RefundAmount]              DECIMAL (14, 2) NULL,
    [NetAmount]                 DECIMAL (14, 2) NULL,
    [TaxCd]                     NVARCHAR (16)   NULL,
    [TaxRate]                   DECIMAL (14, 2) NULL,
    [TaxAmout]                  DECIMAL (14, 2) NULL,
    [AdminChargeAmount]         DECIMAL (14, 2) NULL,
    [AdminChargeNetAmount]      DECIMAL (14, 2) NULL,
    [AdminChargeTaxCd]          NVARCHAR (16)   NULL,
    [AdminChargeTaxRate]        DECIMAL (14, 2) NULL,
    [AdminChargeTaxAmount]      DECIMAL (14, 2) NULL,
    [IsForeignInd]              BIT             NULL,
    [TicketsCancelledDate]      DATETIME        NULL,
    [BookingReference]          NVARCHAR (256)  NULL,
    [ExtReference]              NVARCHAR (256)  NULL,
    [Percentage]                INT             NULL,
    [GrossRefund]               DECIMAL (14, 2) NULL,
    [RequestedDate]             DATETIME        NULL,
    [RefundTypeID]              INT             NULL,
    CONSTRAINT [cndx_PrimaryKey_Refund] PRIMARY KEY CLUSTERED ([RefundID] ASC),
    CONSTRAINT [FK_STG_Refund_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [Staging].[STG_Customer] ([CustomerID]),
    CONSTRAINT [FK_STG_Refund_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID]),
    CONSTRAINT [FK_STG_Refund_RefundDecisionCodeID] FOREIGN KEY ([RefundDecisionCodeID]) REFERENCES [Reference].[RefundDecisionCode] ([RefundDecisionCodeID]),
    CONSTRAINT [FK_STG_Refund_RefundReasonCodeID] FOREIGN KEY ([RefundReasonCodeID]) REFERENCES [Reference].[RefundReasonCode] ([RefundReasonCodeID]),
    CONSTRAINT [FK_STG_Refund_RefundTypeID] FOREIGN KEY ([RefundTypeID]) REFERENCES [Reference].[RefundType] ([RefundTypeID]),
    CONSTRAINT [FK_STG_Refund_RetailChannelID] FOREIGN KEY ([RetailChannelID]) REFERENCES [Reference].[RetailChannel] ([RetailChannelID]),
    CONSTRAINT [FK_STG_Refund_SalesTransactionID] FOREIGN KEY ([SalesTransactionID]) REFERENCES [Staging].[STG_SalesTransaction] ([SalesTransactionID])
);
GO

