CREATE VIEW [Production].[vw_CustomerAggregations]
WITH SCHEMABINDING
AS
     SELECT ISNULL(a.CustomerID, b.CustomerID) AS CustomerID,
			--STG_CustomerAggregation
            ISNULL(a.TransactionsLast12MnthsFirst, 0) AS TransactionsLast12MnthsFirst,
            ISNULL(a.TransactionsLast12MnthsStandard, 0) AS TransactionsLast12MnthsStandard,
            ISNULL(a.TransactionsLast6MnthsFirst, 0) AS TransactionsLast6MnthsFirst,
            ISNULL(a.TransactionsLast6MnthsFirstWeekday, 0) AS TransactionsLast6MnthsFirstWeekday,
            ISNULL(a.TransactionsLast6MnthsFirstWeekend, 0) AS TransactionsLast6MnthsFirstWeekend,
            ISNULL(a.TransactionsLast6MnthsStandard, 0) AS TransactionsLast6MnthsStandard,
            ISNULL(a.TransactionsLast6MnthsStandardWeekday, 0) AS TransactionsLast6MnthsStandardWeekday,
            ISNULL(a.TransactionsLast6MnthsStandardWeekend, 0) AS TransactionsLast6MnthsStandardWeekend,
            ISNULL(a.TransactionsLast12MnthsFirstSolo, 0) AS TransactionsLast12MnthsFirstSolo,
            ISNULL(a.TransactionsLast12MnthsStandardSolo, 0) AS TransactionsLast12MnthsStandardSolo,
            ISNULL(a.TransactionsLast12MnthsFirstWeekday, 0) AS TransactionsLast12MnthsFirstWeekday,
            ISNULL(a.TransactionsLast12MnthsFirstWeekend, 0) AS TransactionsLast12MnthsFirstWeekend,
			--STG_VTWC_CustomerAggregation
            ISNULL(b.[VTWC_SalesTransaction1Mnth], 0) AS VTWC_SalesTransaction1Mnth,
            ISNULL(b.[VTWC_SalesTransaction3Mnth], 0) AS VTWC_SalesTransaction3Mnth,
            ISNULL(b.[VTWC_SalesTransaction6Mnth], 0) AS VTWC_SalesTransaction6Mnth,
            ISNULL(b.[VTWC_TransactionsLast6MnthsFirst], 0) AS VTWC_TransactionsLast6MnthsFirst,
            ISNULL(b.[VTWC_TransactionsLast6MnthsFirstWeekday], 0) AS VTWC_TransactionsLast6MnthsFirstWeekday,
            ISNULL(b.[VTWC_TransactionsLast6MnthsFirstWeekend], 0) AS VTWC_TransactionsLast6MnthsFirstWeekend,
            ISNULL(b.[VTWC_TransactionsLast6MnthsStandard], 0) AS VTWC_TransactionsLast6MnthsStandard,
            ISNULL(b.[VTWC_TransactionsLast6MnthsStandardWeekday], 0) AS VTWC_TransactionsLast6MnthsStandardWeekday,
            ISNULL(b.[VTWC_TransactionsLast6MnthsStandardWeekend], 0) AS VTWC_TransactionsLast6MnthsStandardWeekend,
            ISNULL(b.[VTWC_SalesTransaction12Mnth], 0) AS VTWC_SalesTransaction12Mnth,
            ISNULL(b.[VTWC_TransactionsLast12MnthsFirstSolo], 0) AS VTWC_TransactionsLast12MnthsFirstSolo,
            ISNULL(b.[VTWC_TransactionsLast12MnthsStandardSolo], 0) AS VTWC_TransactionsLast12MnthsStandardSolo,
            ISNULL(b.[VTWC_TransactionsLast12MnthsFirst], 0) AS VTWC_TransactionsLast12MnthsFirst,
            ISNULL(b.[VTWC_TransactionsLast12MnthsStandard], 0) AS VTWC_TransactionsLast12MnthsStandard,
            ISNULL(b.[VTWC_SalesTransactionTotal], 0) AS VTWC_SalesTransactionTotal,
            ISNULL(b.[VTWC_TransactionsLast12MnthsFirstWeekday], 0) AS VTWC_TransactionsLast12MnthsFirstWeekday,
            ISNULL(b.[VTWC_TransactionsLast12MnthsFirstWeekend], 0) AS VTWC_TransactionsLast12MnthsFirstWeekend,
            ISNULL(b.[VTWC_SalesAmountTotal], 0) AS VTWC_SalesAmountTotal,
            ISNULL(b.[VTWC_SalesAmount3Mnth], 0) AS VTWC_SalesAmount3Mnth,
            ISNULL(b.[VTWC_SalesAmount6Mnth], 0) AS VTWC_SalesAmount6Mnth,
            ISNULL(b.[VTWC_SalesAmount12Mnth], 0) AS VTWC_SalesAmount12Mnth,
            b.[VTWC_DateFirstTravelAny],
            b.[VTWC_DateLastTravelAny],
            b.[VTWC_DateNextTravelAny],
            b.[VTWC_DateFirstTravelFirst],
            b.[VTWC_DateLastTravelFirst],
            b.[VTWC_DateNextTravelFirst],
            b.[VTWC_DateFirstPurchaseAny],
            b.[VTWC_DateLastPurchaseAny],
            b.[VTWC_DateFirstPurchaseFirst],
            b.[VTWC_DateLastPurchaseFirst],
            b.[VTWC_DateFirstTravelStandard],
            b.[VTWC_DateLastTravelStandard],
            b.[VTWC_DateNextTravelStandard],
            b.[VTWC_DateFirstPurchaseStandard],
            b.[VTWC_DateLastPurchaseStandard]
     FROM [Staging].[STG_CustomerAggregation] a
          FULL OUTER JOIN [Staging].[STG_VTWC_CustomerAggregation] b ON a.CustomerID = b.CustomerID;