CREATE TABLE [PreProcessing].[Granby_Traveller] (
    [GranbyTravellerID]      INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [EXTERNAL_REFERENCE]     INT            NULL,
    [CUID]                   BIGINT         NULL,
    [TITLE]                  NVARCHAR (255) NULL,
    [FORENAME]               NVARCHAR (255) NULL,
    [SURNAME]                NVARCHAR (255) NULL,
    [GENDER]                 NCHAR (1)      NULL,
    [DAY_TELEPHONE]          NVARCHAR (255) NULL,
    [EVENING_TELEPHONE]      NVARCHAR (255) NULL,
    [FAX_NUM]                NVARCHAR (255) NULL,
    [EMAIL_ADDRESS]          NVARCHAR (255) NULL,
    [HOME_ADDRESS_LINE1]     NVARCHAR (255) NULL,
    [HOME_ADDRESS_LINE2]     NVARCHAR (255) NULL,
    [HOME_ADDRESS_LINE3]     NVARCHAR (255) NULL,
    [HOME_ADDRESS_LINE4]     NVARCHAR (255) NULL,
    [HOME_ADDRESS_LINE5]     NVARCHAR (255) NULL,
    [HOME_POSTCODE]          NVARCHAR (255) NULL,
    [HOME_MAIL_PREF_FLAG]    NCHAR (1)      NULL,
    [HOME_COMPANY_NAME]      NVARCHAR (255) NULL,
    [WORK_ADDRESS_LINE1]     NVARCHAR (255) NULL,
    [WORK_ADDRESS_LINE2]     NVARCHAR (255) NULL,
    [WORK_ADDRESS_LINE3]     NVARCHAR (255) NULL,
    [WORK_ADDRESS_LINE4]     NVARCHAR (255) NULL,
    [WORK_ADDRESS_LINE5]     NVARCHAR (255) NULL,
    [WORK_POSTCODE]          NVARCHAR (255) NULL,
    [WORK_MAIL_PREF_FLAG]    NCHAR (1)      NULL,
    [WORK_COMPANY_NAME]      NVARCHAR (255) NULL,
    [DO_NOT_MAIL_VT]         NCHAR (1)      NULL,
    [LOYALTY_MEMBERSHIP_NUM] NVARCHAR (255) NULL,
    [PASSWORD]               NVARCHAR (255) NULL,
    [EFF_TO_DATE]            DATETIME       NULL,
    [TICKET_VALUE]           DECIMAL (18)   NULL,
    [SOURCE_CODE]            NVARCHAR (255) NULL,
    [CreatedDateETL]         DATETIME       NULL,
    [LastModifiedDateETL]    DATETIME       NULL,
    [ProcessedInd]           BIT            DEFAULT ((0)) NULL,
    [DataImportDetailID]     INT            NULL
);

