CREATE TABLE [PreProcessing].[TOC_RailFare] (
    [TOC_RailFareID]         INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [CustomerId]             INT            NOT NULL,
    [DateCreated]            DATETIME       NOT NULL,
    [DateUpdated]            DATETIME       NOT NULL,
    [ChannelCode]            NVARCHAR (20)  NOT NULL,
    [PurchaseId]             INT            NOT NULL,
    [TransactionId]          INT            NOT NULL,
    [TransactionDate]        DATETIME       NOT NULL,
    [BusinessOrLeisure]      NCHAR (1)      NOT NULL,
    [JourneyId]              INT            NOT NULL,
    [FareId]                 INT            NOT NULL,
    [TicketType]             NVARCHAR (6)   NOT NULL,
    [TicketDesc]             NVARCHAR (50)  NULL,
    [PromoCode]              NVARCHAR (30)  NULL,
    [FullAdultFare]          DECIMAL (6, 2) NULL,
    [DiscAdultFare1]         DECIMAL (6, 2) NULL,
    [DiscAdultFare2]         DECIMAL (6, 2) NULL,
    [DiscAdultFare3]         DECIMAL (6, 2) NULL,
    [FullChildFare]          DECIMAL (6, 2) NULL,
    [DiscChildFare1]         DECIMAL (6, 2) NULL,
    [DiscChildFare2]         DECIMAL (6, 2) NULL,
    [DiscChildFare3]         DECIMAL (6, 2) NULL,
    [NoAdultsFullFare]       INT            NULL,
    [NoAdultsDiscFare1]      INT            NULL,
    [NoAdultsDiscFare2]      INT            NULL,
    [NoAdultsDiscFare3]      INT            NULL,
    [NoChildFullFare]        INT            NULL,
    [NoChildDiscFare1]       INT            NULL,
    [NoChildDiscFare2]       INT            NULL,
    [NoChildDiscFare3]       INT            NULL,
    [Railcard1]              NVARCHAR (5)   NULL,
    [NoRailcard1]            INT            NULL,
    [Railcard2]              NVARCHAR (5)   NULL,
    [NoRailcard2]            INT            NULL,
    [Railcard3]              NVARCHAR (5)   NULL,
    [NoRailcard3]            INT            NULL,
    [NoGroupTicketsFullFare] INT            NULL,
    [NoGroupTicketsDiscFare] INT            NULL,
    [FullGroupFare]          DECIMAL (6, 2) NULL,
    [DiscGroupFare]          DECIMAL (6, 2) NULL,
    CONSTRAINT [cndx_PrimaryKey_TOC_RailFare] PRIMARY KEY CLUSTERED ([TOC_RailFareID] ASC)
);

