CREATE TABLE [PreProcessing].[TOC_Customer] (
    [TOC_CustomerID]      INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Country]             NVARCHAR (30)  NULL,
    [CustomerID]          INT            NOT NULL,
    [CompanyName]         NVARCHAR (64)  NULL,
    [AddressLine1]        NVARCHAR (64)  NULL,
    [AddressLine2]        NVARCHAR (64)  NULL,
    [AddressLine3]        NVARCHAR (64)  NULL,
    [AddressLine4]        NVARCHAR (64)  NULL,
    [AddressLine5]        NVARCHAR (64)  NULL,
    [Town]                NVARCHAR (64)  NULL,
    [County]              NVARCHAR (64)  NULL,
    [Postcode]            NVARCHAR (10)  NULL,
    [DateCreated]         DATETIME       NOT NULL,
    [DateUpdated]         DATETIME       NOT NULL,
    [Title]               NVARCHAR (30)  NULL,
    [Forename]            NVARCHAR (30)  NULL,
    [Surname]             NVARCHAR (60)  NULL,
    [Salutation]          NVARCHAR (60)  NULL,
    [JobTitle]            NVARCHAR (60)  NULL,
    [Gender]              NCHAR (1)      NULL,
    [EveningTelephoneNo]  NVARCHAR (35)  NULL,
    [DayTelephoneNo]      NVARCHAR (35)  NULL,
    [MobileTelephoneNo]   NVARCHAR (35)  NULL,
    [FaxTelephoneNo]      NVARCHAR (35)  NULL,
    [EmailAddress]        NVARCHAR (100) NULL,
    [DateOfBirth]         DATETIME       NULL,
    [FirstCallTranDate]   DATETIME       NULL,
    [FirstIntTranDate]    DATETIME       NULL,
    [FirstMobAppTranDate] DATETIME       NULL,
    [FirstMobWebTranDate] DATETIME       NULL,
    [OptOut]              NCHAR (1)      NULL,
    [ThirdPartyOptOut]    NCHAR (1)      NULL,
    CONSTRAINT [cndx_PrimaryKey_TOC_Customer] PRIMARY KEY CLUSTERED ([TOC_CustomerID] ASC)
);

