CREATE TABLE [PreProcessing].[TOCPLUS_Journey] (
    [TOC_JourneyID]             INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [journeyid]                 BIGINT         NULL,
    [purchaseid]                BIGINT         NULL,
    [tcscustomerid]             BIGINT         NULL,
    [tcstransactionid]          BIGINT         NULL,
    [tcsbookingid]              BIGINT         NULL,
    [transactiondate]           DATETIME       NULL,
    [channelcode]               NVARCHAR (15)  NULL,
    [businessorleisure]         NCHAR (1)      NULL,
    [faresettingtoc]            NVARCHAR (3)   NULL,
    [origstation]               NVARCHAR (50)  NULL,
    [deststation]               NVARCHAR (50)  NULL,
    [reasonfortravel]           NVARCHAR (50)  NULL,
    [outdatedep]                DATETIME       NULL,
    [outdatearr]                DATETIME       NULL,
    [retdatedep]                DATETIME       NULL,
    [retdatearr]                DATETIME       NULL,
    [journeytype]               NCHAR (1)      NULL,
    [travellername]             NVARCHAR (100) NULL,
    [railcarddesc]              NVARCHAR (50)  NULL,
    [railcard1]                 NVARCHAR (5)   NULL,
    [noofrailcards]             INT            NULL,
    [totaladults]               INT            NULL,
    [totalchildren]             INT            NULL,
    [totalreturningadults]      INT            NULL,
    [totalreturningchildren]    INT            NULL,
    [costoftickets]             NUMERIC (6, 2) NULL,
    [totalcost]                 NUMERIC (6, 2) NULL,
    [savingsmade]               NUMERIC (6, 2) NULL,
    [procode]                   NVARCHAR (15)  NULL,
    [tickettypecode]            NVARCHAR (5)   NULL,
    [tickettypedesc]            NVARCHAR (50)  NULL,
    [deliverymethodcode]        NVARCHAR (20)  NULL,
    [deliverymethoddescription] NVARCHAR (50)  NULL,
    [journeydirection]          NVARCHAR (5)   NULL,
    [journeyreference]          NVARCHAR (20)  NULL,
    [cmddateupdated]            DATETIME       NULL,
    [class]                     NCHAR (1)      NULL,
    [origstationcode]           NVARCHAR (5)   NULL,
    [deststationcode]           NVARCHAR (5)   NULL,
    [outboundmileage]           NUMERIC (6, 2) NULL,
    [availabilitycode]          NVARCHAR (5)   NULL,
    [DisabledInd]               NCHAR (1)      NULL,
    [NoFullFareAdults]          INT            NULL,
    [NoDiscFareAdults]          INT            NULL,
    [NoFullFareChildren]        INT            NULL,
    [NoDiscFareChildren]        INT            NULL,
    [DateCreated]               DATETIME       NULL,
    [DateUpdated]               DATETIME       NULL,
    [FareId]                    INT            NULL,
    [PromoCode]                 NVARCHAR (30)  NULL,
    [FullAdultFare]             NUMERIC (6, 2) NULL,
    [DiscAdultFare1]            NUMERIC (6, 2) NULL,
    [DiscAdultFare2]            NUMERIC (6, 2) NULL,
    [DiscAdultFare3]            NUMERIC (6, 2) NULL,
    [FullChildFare]             NUMERIC (6, 2) NULL,
    [DiscChildFare1]            NUMERIC (6, 2) NULL,
    [DiscChildFare2]            NUMERIC (6, 2) NULL,
    [DiscChildFare3]            NUMERIC (6, 2) NULL,
    [NoAdultsFullFare]          INT            NULL,
    [NoAdultsDiscFare1]         INT            NULL,
    [NoAdultsDiscFare2]         INT            NULL,
    [NoAdultsDiscFare3]         INT            NULL,
    [NoChildFullFare]           INT            NULL,
    [NoChildDiscFare1]          INT            NULL,
    [NoChildDiscFare2]          INT            NULL,
    [NoChildDiscFare3]          INT            NULL,
    [NoRailcard1]               INT            NULL,
    [Railcard2]                 NVARCHAR (5)   NULL,
    [NoRailcard2]               INT            NULL,
    [Railcard3]                 NVARCHAR (5)   NULL,
    [NoRailcard3]               INT            NULL,
    [NoGroupTicketsFullFare]    INT            NULL,
    [NoGroupTicketsDiscFare]    INT            NULL,
    [FullGroupFare]             NUMERIC (6, 2) NULL,
    [DiscGroupFare]             NUMERIC (6, 2) NULL,
    [Railcard2Desc]             NVARCHAR (50)  NULL,
    [Railcard3Desc]             NVARCHAR (50)  NULL,
    [FareSettingTOCDesc]        NVARCHAR (50)  NULL,
    [AvailabilityCodeDesc]      NVARCHAR (50)  NULL,
    [CreatedDateETL]            DATETIME       NULL,
    [LastModifiedDateETL]       DATETIME       NULL,
    [ProcessedInd]              BIT            NULL,
    [DataImportDetailID]        INT            NULL,
    CONSTRAINT [cndx_PrimaryKey_TOCPLUS_Journey] PRIMARY KEY CLUSTERED ([TOC_JourneyID] ASC)
);
GO 
CREATE NONCLUSTERED INDEX [idx_TOCPLUS_Journey_DataImportDetailID] ON [PreProcessing].[TOCPLUS_Journey]
(
	[DataImportDetailID] ASC
)
INCLUDE ( 	[TOC_JourneyID],
	[journeyid],
	[ProcessedInd],
	[faresettingtoc],
	[FareSettingTOCDesc],
	[railcarddesc],
	[railcard1],
	[Railcard2],
	[Railcard2Desc],
	[Railcard3],
	[Railcard3Desc],
	[tickettypecode],
	[tickettypedesc],
	[class],
	[deliverymethodcode],
	[deliverymethoddescription]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [idx2_TOCPLUS_Journey_ProcessedInd_DataImportDetailID] ON [PreProcessing].[TOCPLUS_Journey]
(
	[ProcessedInd] ASC,
	[DataImportDetailID] ASC
)
INCLUDE ( 	[TOC_JourneyID],
	[journeyid],
	[purchaseid],
	[tcstransactionid],
	[tcsbookingid],
	[faresettingtoc],
	[outdatedep],
	[outdatearr],
	[retdatedep],
	[retdatearr],
	[journeytype],
	[railcard1],
	[noofrailcards],
	[totaladults],
	[totalchildren],
	[totalreturningadults],
	[totalreturningchildren],
	[costoftickets],
	[totalcost],
	[savingsmade],
	[procode],
	[tickettypecode],
	[deliverymethodcode],
	[journeydirection],
	[journeyreference],
	[cmddateupdated],
	[origstationcode],
	[deststationcode],
	[outboundmileage],
	[availabilitycode],
	[DisabledInd],
	[NoFullFareAdults],
	[NoDiscFareAdults],
	[NoFullFareChildren],
	[NoDiscFareChildren],
	[DateCreated],
	[DateUpdated],
	[FareId],
	[PromoCode],
	[FullAdultFare],
	[DiscAdultFare1],
	[DiscAdultFare2],
	[DiscAdultFare3],
	[FullChildFare],
	[DiscChildFare1],
	[DiscChildFare2],
	[DiscChildFare3],
	[NoAdultsFullFare],
	[NoAdultsDiscFare1],
	[NoAdultsDiscFare2],
	[NoAdultsDiscFare3],
	[NoChildFullFare],
	[NoChildDiscFare1],
	[NoChildDiscFare2],
	[NoChildDiscFare3],
	[NoRailcard1],
	[Railcard2],
	[NoRailcard2],
	[Railcard3],
	[NoRailcard3],
	[NoGroupTicketsFullFare],
	[NoGroupTicketsDiscFare],
	[FullGroupFare],
	[DiscGroupFare]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
go

CREATE NONCLUSTERED INDEX  [idx3_TOCPLUS_Journey_DataImportDetailID]
ON [PreProcessing].[TOCPLUS_Journey] ([DataImportDetailID])
INCLUDE ([CreatedDateETL],[ProcessedInd])
GO

