CREATE VIEW [Railtimetable].[vw_JourneyStagesFULL] AS
SELECT [rid]
      ,[uid]
      ,[trainId]
      ,[ssd]
      ,[toc]
      ,[trainCat]
      ,[isPassengerSvc]
      ,[Stage]
      ,[tpl]
      ,[act]
      ,[plat]
      ,[pta]
      ,[ptd]
      ,[wta]
      ,[wtd]
      ,[cancelReason]
      ,[TimeTableID]
      ,[ssd1]
      ,[LocationID]
  FROM [Railtimetable].[JourneyStages]

  UNION 

  SELECT [rid]
      ,[uid]
      ,[trainId]
      ,[ssd]
      ,[toc]
      ,[trainCat]
      ,[isPassengerSvc]
      ,[Stage]
      ,[tpl]
      ,[act]
      ,[plat]
      ,[pta]
      ,[ptd]
      ,[wta]
      ,[wtd]
      ,[cancelReason]
      ,[TimeTableID]
      ,[ssd1]
      ,[LocationID]
  FROM [Railtimetable].[JourneyStagesArchive]