CREATE TABLE [Reference].[Product] (
    [ProductID]                  INT             IDENTITY (1, 1) NOT NULL,
    [Name]                       NVARCHAR (256)  NOT NULL,
    [Description]                NVARCHAR (4000) NULL,
    [CreatedDate]                DATETIME        NOT NULL,
    [CreatedBy]                  INT             NOT NULL,
    [LastModifiedDate]           DATETIME        NOT NULL,
    [LastModifiedBy]             INT             NOT NULL,
    [ArchivedInd]                BIT             NOT NULL,
    [ProductGroupID]             INT             NULL,
    [TicketTypeCode]             NVARCHAR (8)    NULL,
    [TicketClassID]              INT             NULL,
    [TicketTypeID]               INT             NULL,
    [TicketGroupID]              INT             NULL,
    [TOCIDSpecific]              INT             NULL,
    [ReturnInd]                  BIT             NULL,
    [LongDescription]            NVARCHAR (4000) NULL,
    [SourceCreatedDate]          DATETIME        NULL,
    [SourceModifiedDate]         DATETIME        NULL,
    [IsRailTicketInd]            BIT             NULL,
    [FTOT]                       NVARCHAR (4)    NULL,
    [LTOT]                       NVARCHAR (4)    NULL,
    [IsSeasonTicketInd]          BIT             NULL,
    [SeasonType]                 NVARCHAR (1)    NULL,
    [StartDate]                  DATETIME        NULL,
    [EndDate]                    DATETIME        NULL,
    [TicketValidityID]           INT             NULL,
    [SupplementCode]             NVARCHAR (4)    NULL,
    [SundryCode]                 NVARCHAR (8)    NULL,
    [CapriCode]                  NVARCHAR (8)    NULL,
    [UTSCode]                    INT             NULL,
    [ProductCategoryID]          INT             NULL,
    [TicketSeasonTypeID]         INT             NULL,
    [ShortDescription]           NVARCHAR (256)  NULL,
    [Time_Restriction]           INT             NULL,
    [MinGroup]                   INT             NULL,
    [MaxGroup]                   INT             NULL,
    [MaxNumber]                  INT             NULL,
    [RSPAdvice]                  NVARCHAR (256)  NULL,
    [IDMSDisplayName]            NVARCHAR (256)  NULL,
    [IDMSPrintingName]           NVARCHAR (256)  NULL,
    [IsIDMSAttendedTISInd]       BIT             NULL,
    [IsIDMSUnattendedTISInd]     BIT             NULL,
    [IDMSAdviceMessage]          NVARCHAR (256)  NULL,
    [Format]                     NVARCHAR (4)    NULL,
    [IsNRESApplicableAllTOCsInd] BIT             NULL,
    [NRESFareCategory]           NVARCHAR (32)   NULL,
    [IsNRESIncludesGroupSaveInd] BIT             NULL,
    [NRESName]                   NVARCHAR (256)  NULL,
    [NRESDescription]            NVARCHAR (MAX)  NULL,
    [NRESBreaksJourney]          NVARCHAR (MAX)  NULL,
    [NRESConditionsInfo]         NVARCHAR (MAX)  NULL,
    [NRESAvailabilityInfo]       NVARCHAR (MAX)  NULL,
    [NRESRetailingInfo]          NVARCHAR (MAX)  NULL,
    [NRESBookingDeadlinesInfo]   NVARCHAR (MAX)  NULL,
    [NRESChangesTRVLPlansInfo]   NVARCHAR (MAX)  NULL,
    [NRESRefundsInfo]            NVARCHAR (MAX)  NULL,
    [NRESDiscountsInfo]          NVARCHAR (MAX)  NULL,
    [InformationSourceID]        INT             NULL,
    [ExtReference]               NVARCHAR (256)  NULL,
    CONSTRAINT [cndx_PrimaryKey_Product] PRIMARY KEY CLUSTERED ([ProductID] ASC),
    CONSTRAINT [FK_Product_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID]),
    CONSTRAINT [FK_Product_ProductCategoryID] FOREIGN KEY ([ProductCategoryID]) REFERENCES [Reference].[ProductCategory] ([ProductCategoryID]),
    CONSTRAINT [FK_Product_ProductGroupID] FOREIGN KEY ([ProductGroupID]) REFERENCES [Reference].[ProductGroup] ([ProductGroupID]),
    CONSTRAINT [FK_Product_ProductGroupIDParent] FOREIGN KEY ([ProductGroupID]) REFERENCES [Reference].[ProductGroup] ([ProductGroupID]),
    CONSTRAINT [FK_Product_TicketClassID] FOREIGN KEY ([TicketClassID]) REFERENCES [Reference].[TicketClass] ([TicketClassID]),
    CONSTRAINT [FK_Product_TicketGroupID] FOREIGN KEY ([TicketGroupID]) REFERENCES [Reference].[TicketGroup] ([TicketGroupID]),
    CONSTRAINT [FK_Product_TicketTypeID] FOREIGN KEY ([TicketTypeID]) REFERENCES [Reference].[TicketType] ([TicketTypeID]),
    CONSTRAINT [FK_Product_TOCIDSpecific] FOREIGN KEY ([TOCIDSpecific]) REFERENCES [Reference].[TOC] ([TOCID]),
    CONSTRAINT [FK_TicketSeasonType_TicketSeasonTypeID] FOREIGN KEY ([TicketSeasonTypeID]) REFERENCES [Reference].[TicketSeasonType] ([TicketSeasonTypeID]),
    CONSTRAINT [UC] UNIQUE NONCLUSTERED ([ProductID] ASC, [TicketTypeCode] ASC)
);


GO
CREATE NONCLUSTERED INDEX [idx_Product_ReturnInd]
    ON [Reference].[Product]([ReturnInd] ASC, [InformationSourceID] ASC)
    INCLUDE([FTOT]);

