CREATE TABLE [Production].[Individual] (
    [IndividualID]             INT             NOT NULL,
    [Description]              NVARCHAR (4000) NULL,
    [CreatedDate]              DATETIME        NOT NULL,
    [CreatedBy]                INT             NOT NULL,
    [LastModifiedDate]         DATETIME        NOT NULL,
    [LastModifiedBy]           INT             NOT NULL,
    [ArchivedInd]              BIT             DEFAULT ((0)) NOT NULL,
    [InformationSourceID]      INT             NOT NULL,
    [CustomerTypeID]           INT             NULL,
    [SegmentTierID]            INT             NULL,
    [LocationIDHomeActual]     INT             NULL,
    [LocationIDHomeInferred]   INT             NULL,
    [ValidEmailInd]            BIT             DEFAULT ((0)) NOT NULL,
    [ValidMobileInd]           BIT             DEFAULT ((0)) NOT NULL,
    [OptInLeisureInd]          BIT             DEFAULT ((0)) NOT NULL,
    [OptInCorporateInd]        BIT             DEFAULT ((0)) NOT NULL,
    [IsFallowCellInd]          BIT             DEFAULT ((0)) NOT NULL,
    [CountryID]                INT             CONSTRAINT [DF_ProdIndCountryID] DEFAULT ((-99)) NOT NULL,
    [IsOrganisationInd]        BIT             DEFAULT ((0)) NOT NULL,
    [IsStaffInd]               BIT             DEFAULT ((0)) NOT NULL,
    [IsBlackListInd]           BIT             DEFAULT ((0)) NOT NULL,
    [IsCorporateInd]           BIT             DEFAULT ((0)) NOT NULL,
    [IsTMCInd]                 BIT             DEFAULT ((0)) NOT NULL,
    [RailCardUserInd]          BIT             DEFAULT ((0)) NOT NULL,
    [eVoucherUserInd]          BIT             DEFAULT ((0)) NOT NULL,
    [Salutation]               NVARCHAR (64)   NULL,
    [FirstName]                NVARCHAR (64)   NULL,
    [MiddleName]               NVARCHAR (64)   NULL,
    [LastName]                 NVARCHAR (64)   NULL,
    [EmailAddress]             NVARCHAR (256)  NULL,
    [MobileNumber]             NVARCHAR (512)  NULL,
    [PostalArea]               NVARCHAR (32)   NULL,
    [PostalDistrict]           NVARCHAR (32)   NULL,
    [DateRegistered]           DATETIME        NULL,
    [DateFirstPurchaseAny]     DATETIME        NULL,
    [DateLastPurchaseAny]      DATETIME        NULL,
    [DateFirstPurchaseFirst]   DATETIME        NULL,
    [DateLastPurchaseFirst]    DATETIME        NULL,
    [DateFirstTravelAny]       DATETIME        NULL,
    [DateLastTravelAny]        DATETIME        NULL,
    [DateNextTravelAny]        DATETIME        NULL,
    [DateFirstTravelFirst]     DATETIME        NULL,
    [DateLastTravelFirst]      DATETIME        NULL,
    [DateNextTravelFirst]      DATETIME        NULL,
    [SalesAmountTotal]         DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmount3Mnth]         DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmount6Mnth]         DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmount12Mnth]        DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountRailTotal]     DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountRail3Mnth]     DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountRail6Mnth]     DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountRail12Mnth]    DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountNotRailTotal]  DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountNotRail3Mnth]  DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountNotRail6Mnth]  DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesAmountNotRail12Mnth] DECIMAL (14, 2) DEFAULT ((0)) NULL,
    [SalesTransactionTotal]    INT             DEFAULT ((0)) NULL,
    [SalesTransaction3Mnth]    INT             DEFAULT ((0)) NULL,
    [SalesTransaction6Mnth]    INT             DEFAULT ((0)) NULL,
    [SalesTransaction12Mnth]   INT             DEFAULT ((0)) NULL,
    [RFVsegmentRecency]        CHAR (1)        NULL,
    [RFVsegmentValue]          CHAR (1)        NULL,
    [RFVsegmentFrequency]      CHAR (1)        NULL,
    [RFV]                      VARCHAR(8)      NULL,
    CONSTRAINT [cndx_PrimaryKey_Individual] PRIMARY KEY CLUSTERED ([IndividualID] ASC),
    CONSTRAINT [FK_Individual_CountryID] FOREIGN KEY ([CountryID]) REFERENCES [Reference].[Country] ([CountryID]),
    CONSTRAINT [FK_Individual_CustomerTypeID] FOREIGN KEY ([CustomerTypeID]) REFERENCES [Reference].[CustomerType] ([CustomerTypeID]),
    CONSTRAINT [FK_Individual_IndividualID] FOREIGN KEY ([IndividualID]) REFERENCES [Staging].[STG_Individual] ([IndividualID]),
    CONSTRAINT [FK_Individual_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID]),
    CONSTRAINT [FK_Individual_LocationIDActual] FOREIGN KEY ([LocationIDHomeActual]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_Individual_LocationIDInferred] FOREIGN KEY ([LocationIDHomeInferred]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_Individual_SegmentTierID] FOREIGN KEY ([SegmentTierID]) REFERENCES [Reference].[SegmentTier] ([SegmentTierID])
);


GO
CREATE NONCLUSTERED INDEX [ix_Individual_Optin_Email]
    ON [Production].[Individual]([ArchivedInd] ASC, [OptInLeisureInd] ASC)
    INCLUDE([EmailAddress]);


GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Recency Score for RFV',
    @level0type = N'SCHEMA',
    @level0name = N'Production',
    @level1type = N'TABLE',
    @level1name = N'Individual',
    @level2type = N'COLUMN',
    @level2name = N'RFVsegmentRecency'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Value Score for RFV',
    @level0type = N'SCHEMA',
    @level0name = N'Production',
    @level1type = N'TABLE',
    @level1name = N'Individual',
    @level2type = N'COLUMN',
    @level2name = N'RFVsegmentValue'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'Frequency Score for RFV',
    @level0type = N'SCHEMA',
    @level0name = N'Production',
    @level1type = N'TABLE',
    @level1name = N'Individual',
    @level2type = N'COLUMN',
    @level2name = N'RFVsegmentFrequency'
GO
EXEC sp_addextendedproperty @name = N'MS_Description',
    @value = N'RFV Segmentation',
    @level0type = N'SCHEMA',
    @level0name = N'Production',
    @level1type = N'TABLE',
    @level1name = N'Individual',
    @level2type = N'COLUMN',
    @level2name = N'RFV'