CREATE TABLE [Production].[WebSearchesSummary] (
    [ID]                    BIGINT         IDENTITY (1, 1) NOT NULL,
    [CreatedDate]           DATETIME       DEFAULT (getdate()) NOT NULL,
    [CreatedBy]             INT            NULL,
    [LastModifiedDate]      DATETIME       DEFAULT (getdate()) NOT NULL,
    [LastModifiedBy]        INT            NULL,
    [ArchivedInd]           INT            DEFAULT ((0)) NOT NULL,
    [InformationSourceID]   INT            NULL,
    [IndividualID]          INT            NULL,
    [CustomerID]            INT            NULL,
    [RankLast1Days]         INT            NULL,
    [RankLast3Days]         INT            NULL,
    [RankLast5Days]         INT            NULL,
    [OriginNLC]             NVARCHAR (50)  NULL,
    [OriginStation]         NVARCHAR (256) NULL,
    [DestinationNLC]        NVARCHAR (50)  NULL,
    [DestinationStation]    NVARCHAR (256) NULL,
    [ViaNLC]                NVARCHAR (50)  NULL,
    [ViaStation]            NVARCHAR (256) NULL,
    [AvoidNLC]              NVARCHAR (50)  NULL,
    [AvoidStation]          NVARCHAR (256) NULL,
    [Direct]                CHAR (3)       NULL,
    [OutwardDate]           NVARCHAR (10)  NULL,
    [OutwardTime]           NVARCHAR (16)  NULL,
    [OutwardTimePreference] CHAR (3)       NULL,
    [JourneyType]           NVARCHAR (256) NULL,
    [OpenReturn]            CHAR (3)       NULL,
    [ReturnDate]            NVARCHAR (10)  NULL,
    [ReturnTime]            NVARCHAR (16)  NULL,
    [ReturnTime Preference] CHAR (3)       NULL,
    [NoAdults]              INT            NULL,
    [NoChildren]            INT            NULL,
    [Railcard1Type]         NVARCHAR (512) NULL,
    CONSTRAINT [PK_WebSearchesSummary] PRIMARY KEY CLUSTERED ([ID] ASC)
);

