CREATE FUNCTION [Webtrends].[RailCardSplit](@VALUE1 VARCHAR(MAX))
RETURNS @Railcards TABLE(
	[Railcard1] VARCHAR(MAX) DEFAULT NULL,
	[Railcard2] VARCHAR(MAX) DEFAULT NULL,
	[Railcard3] VARCHAR(MAX) DEFAULT NULL,
	[Railcard4] VARCHAR(MAX) DEFAULT NULL,
	[Railcard5] VARCHAR(MAX) DEFAULT NULL,
	[Railcard6] VARCHAR(MAX) DEFAULT NULL,
	[Railcard7] VARCHAR(MAX) DEFAULT NULL,
	[Railcard8] VARCHAR(MAX) DEFAULT NULL,
	[Railcard9] VARCHAR(MAX) DEFAULT NULL
)
AS
BEGIN
	DECLARE 
		 @VALUE2 VARCHAR(256) = ''
		,@VALUE3 VARCHAR(256) = ''
		,@VALUE4 VARCHAR(256) = ''
		,@VALUE5 VARCHAR(256) = ''
		,@VALUE6 VARCHAR(256) = ''
		,@VALUE7 VARCHAR(256) = ''
		,@VALUE8 VARCHAR(256) = ''

	IF(ISNULL(@VALUE1,'') <> '')
	BEGIN
		SELECT 
			 @VALUE2 = SUBSTRING(@VALUE1,CHARINDEX(';',@VALUE1)+1,LEN(@VALUE1))
			,@VALUE3 = SUBSTRING(@VALUE2,CHARINDEX(';',@VALUE2)+1,LEN(@VALUE2))
			,@VALUE4 = SUBSTRING(@VALUE3,CHARINDEX(';',@VALUE3)+1,LEN(@VALUE3))
			,@VALUE5 = SUBSTRING(@VALUE4,CHARINDEX(';',@VALUE4)+1,LEN(@VALUE4))
			,@VALUE6 = SUBSTRING(@VALUE5,CHARINDEX(';',@VALUE5)+1,LEN(@VALUE5))
			,@VALUE7 = SUBSTRING(@VALUE6,CHARINDEX(';',@VALUE6)+1,LEN(@VALUE6))
			,@VALUE8 = SUBSTRING(@VALUE7,CHARINDEX(';',@VALUE7)+1,LEN(@VALUE7))

		INSERT @Railcards
		SELECT 
			 SUBSTRING(@VALUE1,1,CHARINDEX(';',@VALUE1)-1) [RAILCARD1]
			,SUBSTRING(@VALUE2,1,CHARINDEX(';',@VALUE2)-1) [RAILCARD2]
			,SUBSTRING(@VALUE3,1,CHARINDEX(';',@VALUE3)-1) [RAILCARD3]
			,SUBSTRING(@VALUE4,1,CHARINDEX(';',@VALUE4)-1) [RAILCARD4]
			,SUBSTRING(@VALUE5,1,CHARINDEX(';',@VALUE5)-1) [RAILCARD5]
			,SUBSTRING(@VALUE6,1,CHARINDEX(';',@VALUE6)-1) [RAILCARD6]
			,SUBSTRING(@VALUE7,1,CHARINDEX(';',@VALUE7)-1) [RAILCARD7]
			,SUBSTRING(@VALUE8,1,CHARINDEX(';',@VALUE8)-1) [RAILCARD8]
			,SUBSTRING(@VALUE8,CHARINDEX(';',@VALUE8)+1,LEN(@VALUE8)) [RAILCARD9]
	END
	RETURN
END