CREATE TABLE [Reference].[RailcardType] (
    [RailcardTypeID]            INT             IDENTITY (1, 1) NOT NULL,
    [Name]                      NVARCHAR (256)  NOT NULL,
    [Description]               NVARCHAR (4000) NULL,
    [CreatedDate]               DATETIME        NOT NULL,
    [CreatedBy]                 INT             NOT NULL,
    [LastModifiedDate]          DATETIME        NOT NULL,
    [LastModifiedBy]            INT             NOT NULL,
    [ArchivedInd]               BIT             NOT NULL,
    [ExtReference]              NVARCHAR (256)  NOT NULL,
    [Code]                      NVARCHAR (4)    NULL,
    [AdultStatusCode]           NVARCHAR (4)    NULL,
    [ChildStatusCode]           NVARCHAR (4)    NULL,
    [AAAStatusCode]             NVARCHAR (4)    NULL,
    [StartDate]                 DATETIME        NULL,
    [EndDate]                   DATETIME        NULL,
    [IDMSDisplayName]           NVARCHAR (256)  NULL,
    [IDMSPrintingName]          NVARCHAR (256)  NULL,
    [IDMSAttendedTIS]           BIT             NULL,
    [IDMSUnattendedTIS]         BIT             NULL,
    [CAPRICode]                 NVARCHAR (4)    NULL,
    [QuoteDate]                 DATETIME        NULL,
    [HolderType]                NCHAR (1)       NULL,
    [MinNoOfPassengers]         INT             NULL,
    [MaxNoOfPassengers]         INT             NULL,
    [MinNoOfRailcardHolders]    INT             NULL,
    [MaxNoOfRailcardHolders]    INT             NULL,
    [MinNoOfAccompanyingAdults] INT             NULL,
    [MaxNoOfAccompanyingAdults] INT             NULL,
    [MinNoOfAdults]             INT             NULL,
    [MaxNoOfAdults]             INT             NULL,
    [MinNoOfChildren]           INT             NULL,
    [MaxNoOfChildren]           INT             NULL,
    [PurchasePrice]             INT             NULL,
    [DiscountPrice]             INT             NULL,
    [PeriodOfValidity]          INT             NULL,
    [LastValidDate]             DATETIME        NULL,
    [IsPhysicalCard]            BIT             NULL,
    [SourceCreatedDate]         DATETIME        NULL,
    [SourceModifiedDate]        DATETIME        NULL,
    [IsRestrictedByIssue]       BIT             NULL,
    [IsRestrictedByArea]        BIT             NULL,
    [IsRestrictedByTrain]       BIT             NULL,
    [IsRestrictedByDate]        BIT             NULL,
    [MasterCode]                NVARCHAR (4)    NULL,
    [InformationSourceID]       INT             NOT NULL,
    CONSTRAINT [cndx_PrimaryKey_RailcardType] PRIMARY KEY CLUSTERED ([RailcardTypeID] ASC),
    CONSTRAINT [FK_RailcardType_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID])
);

