CREATE TABLE [PreProcessing].[TOCPLUS_Seasons] (
    [TOCSeasonsID]        INT            IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [season_bookingid]    BIGINT         NULL,
    [tcstransactionid]    BIGINT         NULL,
    [tcscustomerid]       BIGINT         NULL,
    [startdate]           DATETIME       NULL,
    [renewaldate]         DATETIME       NULL,
    [retdatetime]         DATETIME       NULL,
    [flcodeorigin]        NVARCHAR (8)   NULL,
    [flcodedestination]   NVARCHAR (8)   NULL,
    [photocardnumber]     NVARCHAR (10)  NULL,
    [periodtype]          NCHAR (1)      NULL,
    [faresettingtoc]      NVARCHAR (3)   NULL,
    [createdatetime]      DATETIME       NULL,
    [currentsbscode]      NVARCHAR (4)   NULL,
    [paymentmethod]       NVARCHAR (2)   NULL,
    [customercorref]      NVARCHAR (10)  NULL,
    [dmcode]              NVARCHAR (5)   NULL,
    [callinghttp_addr]    NVARCHAR (40)  NULL,
    [tickettclass]        NCHAR (1)      NULL,
    [corpname]            NVARCHAR (40)  NULL,
    [retailercode]        NVARCHAR (6)   NULL,
    [retailerdivision]    NVARCHAR (10)  NULL,
    [role]                NVARCHAR (5)   NULL,
    [tickettype]          NVARCHAR (5)   NULL,
    [totalcostofbooking]  NUMERIC (9, 2) NULL,
    [dateupdated]         DATETIME       NULL,
    [origstationcode]     NVARCHAR (5)   NULL,
    [origstationname]     NVARCHAR (100) NULL,
    [deststationcode]     NVARCHAR (5)   NULL,
    [deststationname]     NVARCHAR (100) NULL,
    [CreatedDateETL]      DATETIME       NULL,
    [LastModifiedDateETL] DATETIME       NULL,
    [ProcessedInd]        BIT            NULL,
    [DataImportDetailID]  INT            NULL,
    CONSTRAINT [cndx_PrimaryKey_TOCPLUS_Seasons] PRIMARY KEY CLUSTERED ([TOCSeasonsID] ASC)
);



