CREATE TABLE [Staging].[STG_RefundDetail] (
    [RefundDetailID]                       INT             IDENTITY (1, 1) NOT FOR REPLICATION NOT NULL,
    [Name]                                 NVARCHAR (256)  NULL,
    [Description]                          NVARCHAR (4000) NULL,
    [CreatedDate]                          DATETIME        NOT NULL,
    [CreatedBy]                            INT             NOT NULL,
    [LastModifiedDate]                     DATETIME        NOT NULL,
    [LastModifiedBy]                       INT             NOT NULL,
    [ArchivedInd]                          BIT             DEFAULT ((0)) NOT NULL,
    [SourceCreatedDate]                    DATETIME        NOT NULL,
    [SourceModifiedDate]                   DATETIME        NOT NULL,
    [InformationSourceID]                  INT             NOT NULL,
    [CustomerID]                           INT             NOT NULL,
    [SalesTransactionID]                   INT             NULL,
    [SalesDetailID]                        INT             NULL,
    [RefundID]                             INT             NOT NULL,
    [ProductID]                            INT             NULL,
    [TicketNumber]                         INT             NULL,
    [RefundAmount]                         DECIMAL (14, 2) NULL,
    [RefundValue]                          DECIMAL (14, 2) NULL,
    [RefundReasonCodeID]                   INT             NULL,
    [RefundTypeID]                         INT             NULL,
    [RefundCategoryCd]                     NVARCHAR (32)   NULL,
    [IsSeasonInd]                          BIT             NULL,
    [SeasonStartDate]                      DATETIME        NULL,
    [SeasonValidity]                       NVARCHAR (8)    NULL,
    [SeasonRefundFrom]                     DATETIME        NULL,
    [NumberOfDays]                         INT             NULL,
    [RefundStatusCd]                       NVARCHAR (16)   NULL,
    [AdjustmentAmount]                     DECIMAL (14, 2) NULL,
    [IsPlusbusOriginInd]                   BIT             NULL,
    [IsTravelcardInd]                      BIT             NULL,
    [IsCarParkInd]                         BIT             NULL,
    [LocationIDOrigin]                     INT             NULL,
    [LocationIDDestination]                INT             NULL,
    [LocationIDOriginTicket]               INT             NULL,
    [LocationIDDestinationTicket]          INT             NULL,
    [SalesTransactionDeplayRepayDate]      DATETIME        NULL,
    [SalesTransactionDeplayRepayDirection] NVARCHAR (8)    NULL,
    [ReissueTypeCd]                        NVARCHAR (32)   NULL,
    [RefundReason]                         NVARCHAR (256)  NULL,
    [RefundAssessmentStatusCd]             NVARCHAR (64)   NULL,
    [LocationIDPlusbusStation]             INT             NULL,
    [LocationIDPlusbus]                    INT             NULL,
    [RouteCode]                            NVARCHAR (8)    NULL,
    [UTSZone]                              INT             NULL,
    [TOCIDPrimary]                         INT             NULL,
    [IsAdultInd]                           BIT             NULL,
    [TicketRestrictionCode]                NVARCHAR (4)    NULL,
    [DepartureDatetime]                    DATETIME        NULL,
    [FareAmount]                           DECIMAL (14, 2) NULL,
    [ExtReference]                         NVARCHAR (256)  NULL,
    CONSTRAINT [cndx_PrimaryKey_RefundDetail] PRIMARY KEY CLUSTERED ([RefundDetailID] ASC),
    CONSTRAINT [FK_STG_RefundDetail_CustomerID] FOREIGN KEY ([CustomerID]) REFERENCES [Staging].[STG_Customer] ([CustomerID]),
    CONSTRAINT [FK_STG_RefundDetail_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID]),
    CONSTRAINT [FK_STG_RefundDetail_LocationIDDestination] FOREIGN KEY ([LocationIDDestination]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_STG_RefundDetail_LocationIDOrigin] FOREIGN KEY ([LocationIDOrigin]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_STG_RefundDetail_LocationIDPlusbus] FOREIGN KEY ([LocationIDPlusbus]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_STG_RefundDetail_LocationIDPlusbusStation] FOREIGN KEY ([LocationIDPlusbusStation]) REFERENCES [Reference].[Location] ([LocationID]),
    CONSTRAINT [FK_STG_RefundDetail_ProductID] FOREIGN KEY ([ProductID]) REFERENCES [Reference].[Product] ([ProductID]),
    CONSTRAINT [FK_STG_RefundDetail_RefundID] FOREIGN KEY ([RefundID]) REFERENCES [Staging].[STG_Refund] ([RefundID]),
    CONSTRAINT [FK_STG_RefundDetail_RefundReasonCodeID] FOREIGN KEY ([RefundReasonCodeID]) REFERENCES [Reference].[RefundReasonCode] ([RefundReasonCodeID]),
    CONSTRAINT [FK_STG_RefundDetail_RefundTypeID] FOREIGN KEY ([RefundTypeID]) REFERENCES [Reference].[RefundType] ([RefundTypeID]),
    CONSTRAINT [FK_STG_RefundDetail_SalesTransactionID] FOREIGN KEY ([SalesTransactionID]) REFERENCES [Staging].[STG_SalesTransaction] ([SalesTransactionID]),
    CONSTRAINT [FK_STG_RefundDetail_TOCIDPrimary] FOREIGN KEY ([TOCIDPrimary]) REFERENCES [Reference].[TOC] ([TOCID])
);

