CREATE TABLE [Staging].[STG_JourneyLeg] (
    [JourneyLegID]              INT             IDENTITY (1, 1) NOT NULL,
    [Name]                      NVARCHAR (256)  NULL,
    [Description]               NVARCHAR (4000) NULL,
    [CreatedDate]               DATETIME        NOT NULL,
    [CreatedBy]                 INT             NOT NULL,
    [LastModifiedDate]          DATETIME        NOT NULL,
    [LastModifiedBy]            INT             NOT NULL,
    [ArchivedInd]               BIT             DEFAULT ((0)) NOT NULL,
    [JourneyID]                 INT             NOT NULL,
    [LegNumber]                 INT             NULL,
    [RSID]                      NVARCHAR (256)  NULL,
    [TicketClassID]             INT             NULL,
    [LocationIDOrigin]          INT             NULL,
    [LocationIDDestination]     INT             NULL,
    [DepartureDateTime]         DATETIME        NULL,
    [InferredDepartureInd]      INT             NULL,
    [ArrivalDateTime]           DATETIME        NULL,
    [InferredArrivalInd]        INT             NULL,
    [TOCID]                     INT             NULL,
    [SeatReservation]           NVARCHAR (256)  NULL,
    [DirectionCd]               NVARCHAR (8)    NULL,
    [DayPlusOne]                BIT             CONSTRAINT [DF_STG_JourneyLeg_DayPlusOne] DEFAULT ((0)) NULL,
    [RecommendedXferTime]       INT             NULL,
    [CateringCode]              NVARCHAR (256)  NULL,
    [JourneyTrainID]            INT             NULL,
    [ExtReference]              NVARCHAR (256)  NULL,
    [InformationSourceID]       INT             NULL,
    [SourceCreatedDate]         DATETIME        NULL,
    [SourceModifiedDate]        DATETIME        NULL,
    [WiFiCode]                  NVARCHAR (32)   NULL,
    [QuietZone_YN]              NCHAR (1)       NULL,
    [TrainUID]                  NVARCHAR (20)   NULL,
    [JLType]                    NCHAR (1)       NULL,
    [CreatedExtractNumber]      INT             NULL,
    [LastModifiedExtractNumber] INT             NULL,
    CONSTRAINT [cndx_PrimaryKey_STG_JourneyLeg] PRIMARY KEY CLUSTERED ([JourneyLegID] ASC),
    CONSTRAINT [FK_STG_JourneyLeg_InformationSourceID] FOREIGN KEY ([InformationSourceID]) REFERENCES [Reference].[InformationSource] ([InformationSourceID]),
    CONSTRAINT [FK_STG_JourneyLeg_JourneyID] FOREIGN KEY ([JourneyID]) REFERENCES [Staging].[STG_Journey] ([JourneyID]),
    CONSTRAINT [FK_STG_JourneyLeg_JourneyTrainID] FOREIGN KEY ([JourneyTrainID]) REFERENCES [Staging].[STG_JourneyTrain] ([JourneyTrainID]),
    CONSTRAINT [FK_STG_JourneyLeg_LocationIDDestination] FOREIGN KEY ([LocationIDDestination]) REFERENCES [Reference].[Station] ([StationID]),
    CONSTRAINT [FK_STG_JourneyLeg_LocationIDOrigin] FOREIGN KEY ([LocationIDOrigin]) REFERENCES [Reference].[Station] ([StationID])
);
GO

