CREATE TABLE [Staging].[STG_VTWC_CustomerAggregation] (
    [CustomerID]                                 INT             NOT NULL,
    [VTWC_SalesTransaction1Mnth]                 INT             NOT NULL,
    [VTWC_SalesTransaction3Mnth]                 INT             NOT NULL,
    [VTWC_SalesTransaction6Mnth]                 INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsFirst]           INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsFirstWeekday]    INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsFirstWeekend]    INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsStandard]        INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsStandardWeekday] INT             NOT NULL,
    [VTWC_TransactionsLast6MnthsStandardWeekend] INT             NOT NULL,
    [VTWC_SalesTransaction12Mnth]                INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsFirstSolo]      INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsStandardSolo]   INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsFirst]          INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsStandard]       INT             NOT NULL,
    [VTWC_SalesTransactionTotal]                 INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsFirstWeekday]   INT             NOT NULL,
    [VTWC_TransactionsLast12MnthsFirstWeekend]   INT             NOT NULL,
    [VTWC_SalesAmountTotal]                      DECIMAL (14, 2) NOT NULL,
    [VTWC_SalesAmount3Mnth]                      DECIMAL (14, 2) NOT NULL,
    [VTWC_SalesAmount6Mnth]                      DECIMAL (14, 2) NOT NULL,
    [VTWC_SalesAmount12Mnth]                     DECIMAL (14, 2) NOT NULL,
    [VTWC_DateFirstTravelAny]                    DATETIME        NULL,
    [VTWC_DateLastTravelAny]                     DATETIME        NULL,
    [VTWC_DateNextTravelAny]                     DATETIME        NULL,
    [VTWC_DateFirstTravelFirst]                  DATETIME        NULL,
    [VTWC_DateLastTravelFirst]                   DATETIME        NULL,
    [VTWC_DateNextTravelFirst]                   DATETIME        NULL,
    [VTWC_DateFirstPurchaseAny]                  DATETIME        NULL,
    [VTWC_DateLastPurchaseAny]                   DATETIME        NULL,
    [VTWC_DateFirstPurchaseFirst]                DATETIME        NULL,
    [VTWC_DateLastPurchaseFirst]                 DATETIME        NULL,
    [VTWC_DateFirstTravelStandard]               DATETIME        NULL,
    [VTWC_DateLastTravelStandard]                DATETIME        NULL,
    [VTWC_DateNextTravelStandard]                DATETIME        NULL,
    [VTWC_DateFirstPurchaseStandard]             DATETIME        NULL,
    [VTWC_DateLastPurchaseStandard]              DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([CustomerID] ASC)
);

