CREATE TABLE [Staging].[STG_LoyaltySeason_Summary] (
    [LoyaltySeasonTicketID]  INT             IDENTITY (1, 1) NOT NULL,
    [Name]                   NVARCHAR (256)  NULL,
    [Description]            NVARCHAR (4000) NULL,
    [CreatedDate]            DATETIME        NOT NULL,
    [CreatedBy]              INT             NOT NULL,
    [LastModifiedDate]       DATETIME        NOT NULL,
    [LastModifiedBy]         INT             NOT NULL,
    [ArchivedInd]            BIT             NOT NULL,
    [SourceCreatedDate]      DATETIME        NOT NULL,
    [SourceModifiedDate]     DATETIME        NOT NULL,
    [CustomerID]             INT             NOT NULL,
    [CBECustomerID]          INT             NOT NULL,
    [SalesTransactionID]     INT             NULL,
    [SalesTransactionNumber] NVARCHAR (256)  NULL,
    [LoyaltyAccountID]       INT             NULL,
    [SalesTransactionDate]   DATETIME        NOT NULL,
    [SalesDetailID]          INT             NULL,
    [LoyaltyPoints]          INT             NULL,
    [LoyaltyCardSchemeName]  NVARCHAR (256)  NULL,
    [OriginalSalesAmount]    DECIMAL (14, 2) NULL,
    [Term]                   INT             NULL,
    [FirstInstDate]          DATE            NULL,
    [LastInstDate]           DATE            NULL,
    [FirstInstAmount]        INT             NULL,
    [RegularInstAmount]      INT             NULL,
    [FinalInstAmount]        INT             NULL,
    [ExtReference]           NVARCHAR (256)  NULL,
    [LoyaltyStatusID]        INT             NULL,
    PRIMARY KEY CLUSTERED ([LoyaltySeasonTicketID] ASC),
    CONSTRAINT [fk_LoyaltyStatusID] FOREIGN KEY ([LoyaltyStatusID]) REFERENCES [Reference].[LoyaltyStatus] ([LoyaltyStatusID])
);

