CREATE TABLE [Staging].[STG_AddressUnique] (
    [AddressUniqueID]     INT             IDENTITY (1, 1) NOT NULL,
    [Name]                NVARCHAR (256)  NULL,
    [Description]         NVARCHAR (4000) NULL,
    [CreatedDate]         DATETIME        NULL,
    [CreatedBy]           NVARCHAR (256)  NULL,
    [LastModifiedDate]    DATETIME        NULL,
    [LastModifiedBy]      INT             NULL,
    [ArchivedInd]         BIT             DEFAULT ((0)) NULL,
    [AverageConfidence]   DECIMAL (5, 2)  NULL,
    [NumberofCustomers]   INT             NULL,
    [NumberofIndividuals] INT             NULL,
    [AddressLine1]        NVARCHAR (512)  NULL,
    [AddressLine2]        NVARCHAR (512)  NULL,
    [AddressLine3]        NVARCHAR (512)  NULL,
    [AddressLine4]        NVARCHAR (512)  NULL,
    [City]                NVARCHAR (512)  NULL,
    [StateProvince]       NVARCHAR (512)  NULL,
    [PostalCode]          NVARCHAR (512)  NULL,
    [Country]             NVARCHAR (512)  NULL,
    [FirmName]            NVARCHAR (512)  NULL,
    [HouseNumber]         NVARCHAR (512)  NULL,
    [StreetName]          NVARCHAR (512)  NULL,
    [Principality]        NVARCHAR (512)  NULL,
    [SubStreet]           NVARCHAR (512)  NULL,
    [County]              NVARCHAR (512)  NULL,
    [ApartmentLabel]      NVARCHAR (512)  NULL,
    [ApartmentNumber]     NVARCHAR (512)  NULL,
    [ApartmentNumber2]    NVARCHAR (512)  NULL,
    [Building]            NVARCHAR (512)  NULL,
    [POBox]               NVARCHAR (512)  NULL,
    [AddressBlock1]       NVARCHAR (512)  NULL,
    [AddressBlock2]       NVARCHAR (512)  NULL,
    [AddressBlock3]       NVARCHAR (512)  NULL,
    [AddressBlock4]       NVARCHAR (512)  NULL,
    [AddressBlock5]       NVARCHAR (512)  NULL,
    [AddressBlock6]       NVARCHAR (512)  NULL,
    [AddressBlock7]       NVARCHAR (512)  NULL,
    [AddressBlock8]       NVARCHAR (512)  NULL,
    [AddressBlock9]       NVARCHAR (512)  NULL,
    CONSTRAINT [cndx_PrimaryKey_STG_AddressUnique] PRIMARY KEY CLUSTERED ([AddressUniqueID] ASC)
);

