CREATE VIEW [CRM].[vw_Ref_Location]
	AS 
SELECT l.[LocationID]
      ,[LocationIDParent]
      ,l.[Name]
	  ,case when g.LocationGroupID is null then 0 else 1 end VTStationInd 
      ,l.[Description]
      ,[TIPLOC]
      ,[NLCCode]
      ,[CRSCode]
      ,[CATEType]
      ,[3AlphaCode]
      ,[3AlphaCodeSub]
      ,[Longitude]
      ,[Latitude]
      ,[Northing]
      ,[Easting]
      ,[ChangeTime]
      ,[DescriptionATOC]
      ,[DescriptionATOC_ATB]
      ,[NLCPlusbus]
      ,[PTECode]
      ,[IsPlusbusInd]
      ,[IsGroupStationInd]
      ,[LondonZoneNumber]
      ,[PartOfAllZones]
      ,[IDMSDisplayName]
      ,[IDMSPrintingName]
      ,[IsIDMSAttendedTISInd]
      ,[IsIDMSUnattendedTISInd]
      ,[IDMSAdviceMessage]
      ,[ExtReference]
      ,[SourceCreatedDate]
      ,[SourceModifiedDate]
      ,l.[CreatedDate]
      ,l.[LastModifiedDate]
from [$(CRMDB)].Reference.Location l 
left join  [$(CRMDB)].[Reference].LocationMapping m  on l.LocationID=m.LocationID
left join  [$(CRMDB)].Reference.LocationMappingType t on m.TypeID=t.TypeID and t.Name='Stations'
left join [$(CRMDB)]. Reference.LocationGroup g on g.LocationGroupID=m.LocationGroupID and g.Name='VT'